services:
  - type: web
    name: saiotaf-backend
    env: python
    buildCommand: pip install -r student-dashboard/backend/requirements.txt && python student-dashboard/backend/manage.py collectstatic --noinput && python student-dashboard/backend/manage.py migrate
    startCommand: gunicorn --chdir student-dashboard/backend config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: USE_SQLITE
        value: "true"
